# Generated by Django 4.2.3 on 2023-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_mobile', models.IntegerField()),
                ('cust_address', models.CharField(max_length=255)),
                ('cust_locality', models.CharField(max_length=50)),
                ('cust_city', models.CharField(max_length=50)),
                ('cust_state', models.CharField(max_length=50)),
                ('cust_pincode', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdt_brand', models.CharField(max_length=50)),
            ],
        ),
    ]
