# Generated by Django 4.2.3 on 2023-07-15 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopper_main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prdt_description',
            field=models.CharField(default=1, max_length=355),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prdt_discounted_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prdt_image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prdt_selling_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='prdt_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_pincode',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='product',
            name='prdt_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopper_main_app.category'),
            preserve_default=False,
        ),
    ]
