# Generated by Django 4.2.3 on 2023-07-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_main_app', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_mobile',
            field=models.CharField(max_length=10),
        ),
    ]
