# Generated by Django 4.2.3 on 2023-07-30 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopper_main_app', '0005_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_mobile',
            field=models.CharField(default=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('mobile', models.CharField(default=10, max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
